name: release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - run: cp target/release/flit-server flit-server-linux-x86_64
      - uses: softprops/action-gh-release@v2
        with:
          files: flit-server-linux-x86_64

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - run: cp target/release/flit-server flit-server-macos-arm64
      - uses: softprops/action-gh-release@v2
        with:
          files: flit-server-macos-arm64

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - run: cp target/release/flit-server.exe flit-server-windows-x86_64.exe
      - uses: softprops/action-gh-release@v2
        with:
          files: flit-server-windows-x86_64.exe
